# Generated by Django 4.0.1 on 2022-05-15 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductKeyTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default='330c0a52-b8a9-45d1-81f3-7ec68d4f84b2', editable=False, max_length=100)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
    ]
