# Generated by Django 4.0.1 on 2022-05-15 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productkeytable',
            options={'verbose_name': 'Product Key'},
        ),
        migrations.AlterField(
            model_name='productkeytable',
            name='key',
            field=models.CharField(default='28cd68fa-20ef-4658-82f7-4a0db11e3b57', max_length=100),
        ),
    ]
