# Generated by Django 4.0.1 on 2022-05-15 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_productkeytable_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productkeytable',
            name='used',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='productkeytable',
            name='key',
            field=models.CharField(default='bc3a9a1b-fbf5-4335-8e9e-3f6cdeeaefa7', max_length=100, verbose_name='Product Key'),
        ),
        migrations.AlterField(
            model_name='productkeytable',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Username'),
        ),
    ]
