# Generated by Django 4.0.1 on 2022-05-17 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_productkeytable_allowed_alter_productkeytable_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productkeytable',
            name='allowed',
            field=models.BooleanField(default=True, verbose_name='Activate / Deactivate'),
        ),
        migrations.AlterField(
            model_name='productkeytable',
            name='key',
            field=models.CharField(default='fbeb18e8-31e4-4d3e-9086-60a262711dd8', max_length=100, verbose_name='Product Key'),
        ),
    ]
