# Generated by Django 4.0.1 on 2022-05-17 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_productkeytable_allowed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productkeytable',
            name='machine_id',
            field=models.CharField(blank=True, max_length=500, verbose_name='Machine ID'),
        ),
        migrations.AlterField(
            model_name='productkeytable',
            name='key',
            field=models.CharField(default='c1599ae4-547c-4dba-a1df-6efb9b6c039d', max_length=100, verbose_name='Product Key'),
        ),
    ]
