# Generated by Django 4.0.1 on 2022-05-17 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_productkeytable_machine_id_alter_productkeytable_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productkeytable',
            name='key',
            field=models.CharField(default='f63d9345-2785-4190-a1d3-3e65ad3f0a3f', max_length=100, verbose_name='Product Key'),
        ),
    ]
