# Generated by Django 4.0.1 on 2022-05-17 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_productkeytable_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productkeytable',
            name='used',
        ),
        migrations.AlterField(
            model_name='productkeytable',
            name='key',
            field=models.CharField(default='2cce0a94-62a0-42c1-8f44-4979944321e4', max_length=100, verbose_name='Product Key'),
        ),
    ]
